name: income_expense_supabase
description: Offline-first income/expense tracker with Flutter + Supabase + Drift
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State & navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Formatting
  intl: ^0.19.0

  # Local database (Drift + SQLite)
  drift: ^2.20.2
  drift_sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3

  # Supabase (Auth + Postgres)
  supabase_flutter: ^2.5.8

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.20.2

flutter:
  uses-material-design: true
